"""Pilot lane B: cells generated by a trained arm of the cell network, for held-out targets (PROTOCOLLO.md §5).

For each requested (key, symbol), n cells are drawn as the model describes them: a library of the held-out key is
drawn in proportion to its pooled controls; k control cells of that library (cell_data.draw_controls_lib, the
training rule) give the context z and the baseline beta; the target's code gives the shift delta and the responder
gate; each cell is a responder with probability pi (a statistical parameter of the mixture); its library size is
drawn from the pooled controls of the key; its counts are negative binomial (Gamma-Poisson) around
L softmax(beta [+ delta]) on the genes the key measures. The dispersion of the held-out study was never trained (no
cell of it entered training): the median over the trained studies of each gene's dispersion is used, and said so.

    py.cmd generate_cells.py --prepass <prepass dir> --arm-dir <training>/<arm> --descriptors <dir with
        descriptors.npy and genes.txt> --targets targets.json --n 32 --out <new file>.npz [--seed 0] [--device cpu]

targets.json: [{"key": "hepg2_nadig|HepG2", "symbol": "TP53"}, ...]. Output: CSR counts on the model genes (data,
indices, indptr, shape), labels (symbol per cell), responder flags, the genes, and a JSON sidecar.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pickle
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import cell_data as CD  # noqa: E402
import cellnet as CN  # noqa: E402


def load_arm(arm_dir: Path, st: dict, descriptors: Path | None, device: str):
    import torch
    m = torch.load(arm_dir / "model.pt", map_location="cpu", weights_only=False)
    symbols = m["symbols"]
    desc = None
    if descriptors is not None and m["target_code"] in ("descriptors", "both"):
        Dm = np.load(descriptors / "descriptors.npy")
        drow = {g: k for k, g in enumerate((descriptors / "genes.txt").read_text(encoding="utf-8").split())}
        desc = np.zeros((len(symbols) + 1, Dm.shape[1]), np.float32)
        for k, s in enumerate(symbols):
            if s in drow:
                desc[k] = Dm[drow[s]]
    model = CN.build_model(len(m["genes"]), len(symbols), len(m["modalities"]), len(m["studies"]),
                           np.asarray(m["input_genes"]), dim=m.get("dim", 128), rank=m.get("rank", 128),
                           target_desc=desc, target_code=m["target_code"], pi_floor=m.get("pi_floor", 0.0),
                           context_mode=m.get("context_mode", "cells"))
    model.load_state_dict(m["state"])
    return model.to(device).eval(), m


def main() -> None:
    import torch
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--prepass", type=Path, required=True)
    p.add_argument("--arm-dir", type=Path, required=True)
    p.add_argument("--descriptors", type=Path)
    p.add_argument("--targets", type=Path, required=True)
    p.add_argument("--n", type=int, default=32, help="cells per target")
    p.add_argument("--ctrl-k", type=int, default=64)
    p.add_argument("--min-own", type=int, default=8)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--device", default="cpu")
    p.add_argument("--out", type=Path, required=True)
    a = p.parse_args()
    if a.out.exists():
        raise SystemExit(f"refusing: {a.out} exists")
    with open(a.prepass / "prepass.pkl", "rb") as fh:
        st = pickle.load(fh)
    model, meta = load_arm(a.arm_dir, st, a.descriptors, a.device)
    if meta["prepass_sha256"] != json.loads((a.prepass / "prepass_done.json").read_text(encoding="utf-8"))["sha256"]:
        raise SystemExit("the model was trained on another prepass state")
    dev = torch.device(a.device)
    G = st["G"]
    kidx = {k: i for i, k in enumerate(st["key_names"])}
    sidx = {s: i for i, s in enumerate(meta["symbols"])}
    gene_pos = {g: i for i, g in enumerate(st["genes"])}
    pool_key, pool_libc = np.asarray(st["pool_key"]), np.asarray(st["pool_libc"])
    lib_rows = {}
    for k in np.unique(pool_key):
        rows_k = np.flatnonzero(pool_key == k)
        lib_rows[int(k)] = {int(l): rows_k[pool_libc[rows_k] == l] for l in np.unique(pool_libc[rows_k])}
    masks = np.stack([s["mask"] for s in st["shards"]])
    masks_in = torch.as_tensor(masks[:, st["input_genes"]], device=dev)
    pool_x = torch.as_tensor(st["pool_x"], device=dev)
    pool_lib_t = torch.as_tensor(st["pool_lib"], device=dev)
    pool_sid = torch.as_tensor(np.asarray(st["pool_sid"], np.int64), device=dev)
    trained = [i for i, s in enumerate(meta["studies"]) if s not in {k.split("|", 1)[0] for k in st["held_keys"]}]
    theta = torch.exp(model.log_theta[trained].detach()).median(0).values.clamp(1e-3, 1e4).to(dev)
    mod_of_key = {}
    for s in st["shards"]:
        for k, md in zip(np.asarray(s["key"]), np.asarray(s["mod"])):
            mod_of_key.setdefault(int(k), int(md))
    targets = json.loads(a.targets.read_text(encoding="utf-8"))
    rng = np.random.default_rng(a.seed)
    torch.manual_seed(a.seed)
    datas, indices, indptr, labels, resp_all = [], [], [0], [], []
    report = []
    with torch.no_grad():
        for t in targets:
            k = kidx[t["key"]]
            libs = lib_rows[k]
            names = sorted(libs)
            sizes = np.array([len(libs[l]) for l in names], float)
            chosen = rng.choice(len(names), size=a.n, p=sizes / sizes.sum())
            measured = torch.as_tensor(st["key_mask"][k], device=dev)
            tgt = sidx.get(t["symbol"], len(meta["symbols"]))
            tg = gene_pos.get(t["symbol"], -1)
            lib_pool = np.asarray(st["pool_lib"])[np.concatenate(list(libs.values()))]
            for li in np.unique(chosen):
                n = int((chosen == li).sum())
                rows, how = CD.draw_controls_lib(lib_rows, k, names[li], a.ctrl_k, rng, a.min_own)
                r = torch.as_tensor(rows[None, :], device=dev)
                z, beta = model.context(pool_x[r].float(), masks_in[pool_sid[r]], pool_lib_t[r])
                delta, gate = model(z, beta, torch.tensor([tgt], device=dev), torch.tensor([tg], device=dev),
                                    torch.tensor([mod_of_key[k]], device=dev))
                pi = float(model.pi_of(gate)[0])
                p0 = torch.softmax(beta[0].masked_fill(~measured, float("-inf")), -1)
                p1 = torch.softmax((beta[0] + delta[0]).masked_fill(~measured, float("-inf")), -1)
                resp = rng.random(n) < pi
                L = torch.as_tensor(rng.choice(lib_pool, size=n, replace=True), device=dev, dtype=torch.float32)
                mu = L[:, None] * torch.where(torch.as_tensor(resp, device=dev)[:, None], p1[None, :], p0[None, :])
                g = torch.distributions.Gamma(theta[None, :].expand_as(mu), (theta[None, :] / mu.clamp_min(1e-12)))
                counts = torch.poisson(g.sample()).cpu().numpy() * st["key_mask"][k][None, :]
                for row in counts:
                    nz = np.flatnonzero(row)
                    datas.append(row[nz].astype(np.float32))
                    indices.append(nz.astype(np.int32))
                    indptr.append(indptr[-1] + nz.size)
                labels += [t["symbol"]] * n
                resp_all += resp.tolist()
                report.append({"key": t["key"], "symbol": t["symbol"], "library": int(names[li]), "cells": n,
                               "pi": pi, "draw": CD.FALLBACK[how], "target_known": tgt < len(meta["symbols"])})
    a.out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(a.out, data=np.concatenate(datas) if datas else np.zeros(0, np.float32),
                        indices=np.concatenate(indices) if indices else np.zeros(0, np.int32),
                        indptr=np.asarray(indptr, np.int64), shape=np.array([len(labels), G]),
                        labels=np.array(labels), responder=np.array(resp_all, bool), genes=np.array(st["genes"]))
    side = {"arm": str(a.arm_dir), "target_code": meta["target_code"], "context_mode": meta.get("context_mode"),
            "prepass_sha256": meta["prepass_sha256"], "cells": len(labels), "targets": len(targets), "n": a.n,
            "seed": a.seed, "dispersion": "median over trained studies of exp(log_theta) per gene",
            "blocks": report, "sha256": hashlib.sha256(a.out.read_bytes()).hexdigest()}
    a.out.with_suffix(".json").write_text(json.dumps(side, indent=1), encoding="utf-8")
    print(json.dumps({k: side[k] for k in ("cells", "targets", "target_code", "context_mode")}))


if __name__ == "__main__":
    main()
