"""Tests for the pairwise-loss numerical oracle.

Expected numbers are calculated here with Fraction arithmetic, not by
calling the verifier. Fixtures are synthetic and tiny on purpose.
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import subprocess
import sys
import tempfile
import unittest
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from oracle.cli import EXIT, main as cli_main  # noqa: E402
from oracle.pairwise_loss import (  # noqa: E402
    ERROR, FAIL, PASS, UNVERIFIED, VERIFIER_VERSION,
    overall_verdict, verify_bytes, verify_paths, CheckOutcome,
)

FIXTURES = ROOT / "src" / "oracle" / "fixtures" / "pairwise_loss"

# Hand calculation for example.csv. Do not replace these with verifier output.
# mean_a = (0.20 + 0.40 + 0.30) / 3 = 0.90 / 3 = 0.30
# mean_b = (0.30 + 0.35 + 0.40) / 3 = 1.05 / 3 = 0.35
# delta  = ((0.20-0.30) + (0.40-0.35) + (0.30-0.40)) / 3
#        = (-0.10 + 0.05 + -0.10) / 3 = -0.15 / 3 = -0.05
EXAMPLE_MEAN_A = (Fraction("0.20") + Fraction("0.40") + Fraction("0.30")) / 3
EXAMPLE_MEAN_B = (Fraction("0.30") + Fraction("0.35") + Fraction("0.40")) / 3
EXAMPLE_DELTA = (
    (Fraction("0.20") - Fraction("0.30"))
    + (Fraction("0.40") - Fraction("0.35"))
    + (Fraction("0.30") - Fraction("0.40"))
) / 3
SWAPPED_MEAN_A = EXAMPLE_MEAN_B
SWAPPED_MEAN_B = EXAMPLE_MEAN_A
SWAPPED_DELTA = -EXAMPLE_DELTA


def within_tol(declared: Fraction, recomputed: Fraction,
               abs_tol: Fraction, rel_tol: Fraction) -> bool:
    """Contract §3.1, copied here so expected matches are not generated
    by the function under test."""
    return abs(declared - recomputed) <= abs_tol + rel_tol * abs(recomputed)


def conclusion_from_contract(delta: Fraction, tau: Fraction) -> str:
    """Copy of the contract rule, kept here so expected verdicts are not
    generated by the function under test."""
    if abs(delta) <= tau:
        return "equivalent_within_tolerance"
    if delta < 0:
        return "A_lower"
    return "B_lower"


def status(report, check_id: str) -> str:
    return next(c.status for c in report.checks if c.id == check_id)


def reason(report, check_id: str) -> str:
    return next(c.reason for c in report.checks if c.id == check_id)


def run(csv_name: str, candidate_name: str, config_name: str | None = "config_default.json"):
    config = None if config_name is None else FIXTURES / config_name
    return verify_paths(FIXTURES / csv_name, FIXTURES / candidate_name, config)


class HandCalculationTests(unittest.TestCase):
    """The known results exist before the verifier is asked anything."""

    def test_example_means_are_exact_tenths(self):
        self.assertEqual(EXAMPLE_MEAN_A, Fraction(3, 10))
        self.assertEqual(EXAMPLE_MEAN_B, Fraction(7, 20))
        self.assertEqual(EXAMPLE_DELTA, Fraction(-1, 20))
        self.assertEqual(EXAMPLE_MEAN_A - EXAMPLE_MEAN_B, EXAMPLE_DELTA)

    def test_swapped_means(self):
        self.assertEqual(SWAPPED_MEAN_A, Fraction(7, 20))
        self.assertEqual(SWAPPED_MEAN_B, Fraction(3, 10))
        self.assertEqual(SWAPPED_DELTA, Fraction(1, 20))

    def test_boundary_rule_is_closed_interval(self):
        tau = Fraction("0.05")
        self.assertEqual(conclusion_from_contract(Fraction("-0.05"), tau),
                         "equivalent_within_tolerance")
        self.assertEqual(conclusion_from_contract(Fraction("0.05"), tau),
                         "equivalent_within_tolerance")
        self.assertEqual(conclusion_from_contract(Fraction("-0.0500001"), tau), "A_lower")
        self.assertEqual(conclusion_from_contract(Fraction("0.0500001"), tau), "B_lower")
        self.assertEqual(conclusion_from_contract(Fraction("-0.049"), tau),
                         "equivalent_within_tolerance")
        self.assertEqual(conclusion_from_contract(Fraction(0), Fraction(0)),
                         "equivalent_within_tolerance")
        self.assertEqual(conclusion_from_contract(Fraction("-0.01"), Fraction(0)), "A_lower")


class CorrectAndIncorrectClaims(unittest.TestCase):
    def test_correct_candidate_passes(self):
        report = run("example.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, PASS)
        self.assertEqual(report.n_cases, 3)
        self.assertEqual(report.recomputed.mean_loss_a, EXAMPLE_MEAN_A)
        self.assertEqual(report.recomputed.mean_loss_b, EXAMPLE_MEAN_B)
        self.assertEqual(report.recomputed.mean_difference, EXAMPLE_DELTA)
        self.assertEqual(report.recomputed.conclusion, "A_lower")
        self.assertTrue(all(c.status == PASS for c in report.checks))

    def test_wrong_declared_mean_fails(self):
        report = run("example.csv", "wrong_mean.json")
        self.assertEqual(report.verdict, FAIL)
        self.assertEqual(status(report, "declared_values"), FAIL)
        self.assertEqual(status(report, "declared_conclusion"), PASS)
        self.assertIn("mean_loss_a", reason(report, "declared_values"))

    def test_inverted_difference_sign_fails(self):
        report = run("example.csv", "inverted_difference.json")
        self.assertEqual(report.verdict, FAIL)
        self.assertEqual(status(report, "declared_values"), FAIL)
        self.assertIn("mean_difference", reason(report, "declared_values"))
        comparison = next(v for v in report.value_comparisons
                          if v["name"] == "mean_difference")
        self.assertEqual(comparison["declared"], "0.05")
        self.assertEqual(comparison["recomputed"], "-0.05")

    def test_wrong_declared_winner_fails(self):
        report = run("example.csv", "wrong_winner.json")
        self.assertEqual(report.verdict, FAIL)
        self.assertEqual(status(report, "declared_values"), PASS)
        self.assertEqual(status(report, "declared_conclusion"), FAIL)
        self.assertEqual(report.conclusion_comparison["declared"], "B_lower")
        self.assertEqual(report.conclusion_comparison["recomputed"], "A_lower")

    def test_b_lower_on_swapped_csv_passes(self):
        report = run("swapped.csv", "b_lower_candidate.json")
        self.assertEqual(report.verdict, PASS)
        self.assertEqual(report.recomputed.mean_difference, SWAPPED_DELTA)
        self.assertEqual(report.recomputed.conclusion, "B_lower")


class EquivalenceAndBoundary(unittest.TestCase):
    def test_inside_equivalence_threshold_passes(self):
        report = run("example.csv", "equivalent_candidate.json",
                     "config_equivalence_wide.json")
        self.assertEqual(report.verdict, PASS)
        self.assertEqual(report.recomputed.conclusion, "equivalent_within_tolerance")
        self.assertEqual(report.config.equivalence_threshold, Fraction("0.10"))

    def test_at_threshold_is_equivalent_not_a_winner(self):
        report = run("example.csv", "equivalent_candidate.json",
                     "config_boundary.json")
        self.assertEqual(report.verdict, PASS)
        self.assertEqual(report.recomputed.conclusion, "equivalent_within_tolerance")
        self.assertEqual(abs(report.recomputed.mean_difference),
                         report.config.equivalence_threshold)

    def test_declaring_a_winner_at_the_boundary_fails(self):
        report = run("example.csv", "correct_candidate.json", "config_boundary.json")
        self.assertEqual(report.verdict, FAIL)
        self.assertEqual(status(report, "declared_conclusion"), FAIL)
        self.assertEqual(report.conclusion_comparison["recomputed"],
                         "equivalent_within_tolerance")

    def test_just_beyond_threshold_is_a_winner(self):
        report = run("example.csv", "correct_candidate.json",
                     "config_just_inside_winner.json")
        self.assertEqual(report.verdict, PASS)
        self.assertEqual(report.recomputed.conclusion, "A_lower")
        self.assertGreater(
            abs(report.recomputed.mean_difference),
            report.config.equivalence_threshold,
        )


class StructuralErrors(unittest.TestCase):
    def test_duplicate_ids_are_error_and_do_not_recompute(self):
        report = run("duplicate_ids.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "identifiers"), ERROR)
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertIsNone(report.recomputed)
        self.assertIn("duplicato", reason(report, "identifiers"))

    def test_missing_value_is_error_no_silent_drop(self):
        report = run("missing_value.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "finite_values"), ERROR)
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertEqual(report.n_cases, 3)
        self.assertIsNone(report.recomputed)

    def test_nan_is_error(self):
        report = run("nan_value.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "finite_values"), ERROR)
        self.assertIn("non finito", reason(report, "finite_values"))

    def test_infinity_is_error(self):
        report = run("inf_value.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "finite_values"), ERROR)

    def test_empty_csv_header_only_is_error(self):
        report = run("empty.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "csv_readable"), ERROR)
        self.assertEqual(status(report, "identifiers"), UNVERIFIED)
        self.assertEqual(status(report, "recompute"), UNVERIFIED)

    def test_empty_file_is_error(self):
        report = run("empty_file.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "csv_readable"), ERROR)

    def test_comma_decimal_is_error(self):
        report = run("comma_decimal.csv", "correct_candidate.json")
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "finite_values"), ERROR)
        self.assertIn("separatore decimale", reason(report, "finite_values"))

    def test_missing_csv_is_unverified(self):
        report = verify_paths(FIXTURES / "no_such.csv",
                              FIXTURES / "correct_candidate.json",
                              FIXTURES / "config_default.json")
        self.assertEqual(report.verdict, UNVERIFIED)
        self.assertEqual(status(report, "csv_readable"), UNVERIFIED)

    def test_missing_claim_field_is_unverified_but_still_recomputes(self):
        report = run("example.csv", "missing_mean.json")
        self.assertEqual(report.verdict, UNVERIFIED)
        self.assertEqual(status(report, "candidate_readable"), UNVERIFIED)
        self.assertEqual(status(report, "recompute"), PASS)
        self.assertEqual(report.recomputed.mean_loss_a, EXAMPLE_MEAN_A)
        self.assertEqual(status(report, "declared_values"), UNVERIFIED)


class CandidateCannotDictateRules(unittest.TestCase):
    def test_candidate_tolerance_is_ignored_when_numbers_are_correct(self):
        report = run("example.csv", "imposes_tolerance.json")
        self.assertEqual(report.verdict, PASS)
        self.assertIn("abs_tol", report.ignored_candidate_fields)
        self.assertIn("equivalence_threshold", report.ignored_candidate_fields)
        self.assertEqual(report.config.abs_tol, Fraction(1, 10 ** 12))
        self.assertEqual(report.config.equivalence_threshold, Fraction("0.01"))
        self.assertEqual(report.config.source, "operator")

    def test_candidate_tolerance_does_not_rescue_a_wrong_mean(self):
        report = run("example.csv", "imposes_tolerance_wrong_mean.json")
        self.assertEqual(report.verdict, FAIL)
        self.assertEqual(status(report, "declared_values"), FAIL)
        self.assertEqual(report.config.abs_tol, Fraction(1, 10 ** 12))
        declared = Fraction("0.31")
        self.assertFalse(within_tol(declared, EXAMPLE_MEAN_A,
                                    Fraction(1, 10 ** 12), Fraction(0)))
        self.assertTrue(within_tol(declared, EXAMPLE_MEAN_A,
                                   Fraction(1), Fraction(0)))


class ReportContract(unittest.TestCase):
    def test_hashes_are_of_bytes_actually_read(self):
        report = run("example.csv", "correct_candidate.json")
        csv_bytes = (FIXTURES / "example.csv").read_bytes()
        cand_bytes = (FIXTURES / "correct_candidate.json").read_bytes()
        cfg_bytes = (FIXTURES / "config_default.json").read_bytes()
        self.assertEqual(report.inputs["csv_sha256"],
                         hashlib.sha256(csv_bytes).hexdigest())
        self.assertEqual(report.inputs["candidate_sha256"],
                         hashlib.sha256(cand_bytes).hexdigest())
        self.assertEqual(report.inputs["config_sha256"],
                         hashlib.sha256(cfg_bytes).hexdigest())

    def test_report_contains_limits_and_version(self):
        payload = run("example.csv", "correct_candidate.json").to_dict()
        self.assertEqual(payload["verifier"]["version"], VERIFIER_VERSION)
        self.assertGreaterEqual(len(payload["limits"]), 4)
        joined = " ".join(payload["limits"])
        self.assertIn("generalizza", joined)
        self.assertIn("statisticamente", joined)
        self.assertIn("biologicamente", joined)
        self.assertIn("protocollo", joined)
        summary = run("example.csv", "correct_candidate.json").summary_text()
        self.assertIn("Esito complessivo: PASS", summary)
        self.assertIn("0.3", summary)
        self.assertEqual(payload["recomputed"]["mean_loss_a_exact"], "3/10")
        self.assertEqual(payload["report_rounding"]["mode"], "half_even")
        self.assertNotIn(",", payload["recomputed"]["mean_loss_a"])

    def test_pass_requires_every_required_check(self):
        incomplete = [CheckOutcome("csv_readable", PASS, "ok")]
        self.assertEqual(overall_verdict(incomplete), ERROR)

    def test_numeric_format_uses_decimal_point(self):
        payload = run("example.csv", "correct_candidate.json").to_dict()
        for key in ("mean_loss_a", "mean_loss_b", "mean_difference"):
            self.assertRegex(payload["recomputed"][key], r"^-?\d+\.\d+$")


class ReviewRegression(unittest.TestCase):
    """The three cases reproduced in the review, byte-for-byte.

    Expected exact values are computed here with Fraction, not by the
    verifier.
    """

    REVIEW_MEANS_CSV = (
        b"case_id,loss_a,loss_b\n"
        b"c1,1,2\n"
        b"c2,0,0\n"
        b"c3,0,0\n"
    )
    REVIEW_MEANS_CANDIDATE = (
        b'{"mean_loss_a": 0.3333333333333333,'
        b' "mean_loss_b": 0.6666666666666666,'
        b' "mean_difference": -0.3333333333333333,'
        b' "conclusion": "A_lower"}'
    )
    REVIEW_DUPLICATE_HEADERS_CSV = (
        b"case_id,loss_a,loss_b,loss_a\n"
        b"c1,0.20,0.30,0.99\n"
        b"c2,0.40,0.35,0.99\n"
        b"c3,0.30,0.40,0.99\n"
    )
    REVIEW_OVERFLOW_CSV = b"case_id,loss_a,loss_b\nc1,1e1000000,0\n"

    def test_rounded_decimal_means_are_exact_thirds(self):
        # (1+0+0)/3 = 1/3, (2+0+0)/3 = 2/3, delta = -1/3.
        mean_a = (Fraction(1) + Fraction(0) + Fraction(0)) / 3
        mean_b = (Fraction(2) + Fraction(0) + Fraction(0)) / 3
        delta = mean_a - mean_b
        self.assertEqual(mean_a, Fraction(1, 3))
        self.assertEqual(mean_b, Fraction(2, 3))
        self.assertEqual(delta, Fraction(-1, 3))
        self.assertEqual(
            ((Fraction(1) - Fraction(2)) + (Fraction(0) - Fraction(0))
             + (Fraction(0) - Fraction(0))) / 3,
            delta,
        )

        report = verify_bytes(self.REVIEW_MEANS_CSV, self.REVIEW_MEANS_CANDIDATE, None)
        self.assertEqual(status(report, "recompute"), PASS)
        self.assertNotIn("errore interno", reason(report, "recompute"))
        self.assertEqual(report.recomputed.mean_loss_a, Fraction(1, 3))
        self.assertEqual(report.recomputed.mean_loss_b, Fraction(2, 3))
        self.assertEqual(report.recomputed.mean_difference, Fraction(-1, 3))
        self.assertEqual(report.recomputed.conclusion, "A_lower")
        self.assertEqual(report.verdict, PASS)
        payload = report.to_dict()
        self.assertEqual(payload["recomputed"]["mean_loss_a_exact"], "1/3")
        self.assertNotEqual(payload["recomputed"]["mean_loss_a"], "1/3")

    def test_duplicate_headers_are_error_and_do_not_read_the_last_column(self):
        report = verify_bytes(
            self.REVIEW_DUPLICATE_HEADERS_CSV,
            (FIXTURES / "correct_candidate.json").read_bytes(),
            None,
        )
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "csv_readable"), ERROR)
        self.assertIn("intestazioni duplicate", reason(report, "csv_readable"))
        self.assertIn("loss_a", reason(report, "csv_readable"))
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertIsNone(report.recomputed)

    def test_overflow_token_is_error_without_raising(self):
        report = verify_bytes(
            self.REVIEW_OVERFLOW_CSV,
            b'{"mean_loss_a": 0, "mean_loss_b": 0,'
            b' "mean_difference": 0, "conclusion": "equivalent_within_tolerance"}',
            None,
        )
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "finite_values"), ERROR)
        self.assertIn("esponente", reason(report, "finite_values"))
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertIsNone(report.recomputed)


class JsonNumberTypeTests(unittest.TestCase):
    """JSON numbers are not strings. Tokens are not converted to float."""

    CSV = b"case_id,loss_a,loss_b\nc1,0.20,0.30\n"
    NUMBER_CANDIDATE = (
        b'{"mean_loss_a": 0.2, "mean_loss_b": 0.3,'
        b' "mean_difference": -0.1, "conclusion": "A_lower"}'
    )

    def test_json_numbers_including_scientific_notation_are_accepted(self):
        scientific = (
            b'{"mean_loss_a": 3.0e-1, "mean_loss_b": 3.5e-1,'
            b' "mean_difference": -5.0e-2, "conclusion": "A_lower"}'
        )
        report = verify_bytes(
            (FIXTURES / "example.csv").read_bytes(),
            scientific,
            None,
        )
        self.assertEqual(status(report, "candidate_readable"), PASS)
        self.assertEqual(report.verdict, PASS)
        self.assertEqual(report.recomputed.mean_loss_a, EXAMPLE_MEAN_A)
        self.assertEqual(report.recomputed.mean_loss_b, EXAMPLE_MEAN_B)
        self.assertEqual(report.recomputed.mean_difference, EXAMPLE_DELTA)
        self.assertEqual(report.claim.mean_loss_a, Fraction(3, 10))
        self.assertEqual(report.claim.mean_loss_b, Fraction(7, 20))
        self.assertEqual(report.claim.mean_difference, Fraction(-1, 20))

    def test_numeric_strings_in_candidate_are_type_error(self):
        candidate = (
            b'{"mean_loss_a": "0.2", "mean_loss_b": "0.3",'
            b' "mean_difference": "-0.1", "conclusion": "A_lower"}'
        )
        report = verify_bytes(self.CSV, candidate, None)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "candidate_readable"), ERROR)
        self.assertIn("str", reason(report, "candidate_readable"))

    def test_numeric_strings_in_config_are_type_error(self):
        config = b'{"abs_tol": "1e-12", "rel_tol": 0, "equivalence_threshold": 0.01}'
        report = verify_bytes(self.CSV, self.NUMBER_CANDIDATE, config)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "operator_config"), ERROR)
        self.assertIn("str", reason(report, "operator_config"))
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertIsNone(report.recomputed)

    def test_boolean_in_candidate_is_type_error(self):
        candidate = (
            b'{"mean_loss_a": true, "mean_loss_b": 0.3,'
            b' "mean_difference": -0.1, "conclusion": "A_lower"}'
        )
        report = verify_bytes(self.CSV, candidate, None)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "candidate_readable"), ERROR)
        self.assertIn("bool", reason(report, "candidate_readable"))

    def test_boolean_in_config_is_type_error(self):
        config = b'{"abs_tol": false, "rel_tol": 0, "equivalence_threshold": 0.01}'
        report = verify_bytes(self.CSV, self.NUMBER_CANDIDATE, config)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "operator_config"), ERROR)
        self.assertIn("bool", reason(report, "operator_config"))

    def test_non_finite_json_constants_are_error(self):
        for raw in (b"NaN", b"Infinity", b"-Infinity"):
            candidate = (
                b'{"mean_loss_a": ' + raw + b', "mean_loss_b": 0.3,'
                b' "mean_difference": -0.1, "conclusion": "A_lower"}'
            )
            report = verify_bytes(self.CSV, candidate, None)
            self.assertEqual(report.verdict, ERROR)
            self.assertEqual(status(report, "candidate_readable"), ERROR)
            self.assertIn("non finito", reason(report, "candidate_readable"))


class CsvParserErrorTests(unittest.TestCase):
    """csv.Error must become csv_readable: error, not an uncaught exception."""

    CANDIDATE = (
        b'{"mean_loss_a": 0.2, "mean_loss_b": 0.3,'
        b' "mean_difference": -0.1, "conclusion": "A_lower"}'
    )

    def _oversize_token(self) -> str:
        return "x" * (csv.field_size_limit() + 1)

    def test_oversize_header_field_is_csv_readable_error(self):
        huge = self._oversize_token()
        csv_bytes = f"case_id,{huge},loss_b\nc1,0.20,0.30\n".encode()
        report = verify_bytes(csv_bytes, self.CANDIDATE, None)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "csv_readable"), ERROR)
        self.assertIn("non parsabile", reason(report, "csv_readable"))
        self.assertEqual(status(report, "identifiers"), UNVERIFIED)
        self.assertEqual(status(report, "finite_values"), UNVERIFIED)
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertIsNone(report.recomputed)

    def test_oversize_data_field_is_csv_readable_error(self):
        huge = self._oversize_token()
        csv_bytes = f"case_id,loss_a,loss_b\nc1,{huge},0.30\n".encode()
        report = verify_bytes(csv_bytes, self.CANDIDATE, None)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "csv_readable"), ERROR)
        self.assertIn("non parsabile", reason(report, "csv_readable"))
        self.assertEqual(status(report, "recompute"), UNVERIFIED)
        self.assertIsNone(report.recomputed)

    def test_cli_oversize_field_writes_report_and_exits_3_without_traceback(self):
        huge = self._oversize_token()
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            csv_path = tmp_path / "huge.csv"
            csv_path.write_text(
                f"case_id,loss_a,loss_b\nc1,{huge},0.30\n",
                encoding="utf-8",
                newline="\n",
            )
            candidate_path = tmp_path / "candidate.json"
            candidate_path.write_bytes(self.CANDIDATE)
            report_path = tmp_path / "report.json"
            summary_path = tmp_path / "summary.txt"
            env = os.environ.copy()
            env["PYTHONPATH"] = str(ROOT / "src")
            env["PYTHONIOENCODING"] = "utf-8"
            proc = subprocess.run(
                [
                    sys.executable, "-m", "oracle",
                    "--csv", str(csv_path),
                    "--candidate", str(candidate_path),
                    "--report", str(report_path),
                    "--summary", str(summary_path),
                ],
                cwd=str(ROOT),
                env=env,
                capture_output=True,
                text=True,
            )
            self.assertEqual(proc.returncode, EXIT[ERROR])
            self.assertNotIn("Traceback", proc.stderr)
            self.assertNotIn("Traceback", proc.stdout)
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["verdict"], "error")
            self.assertEqual(payload["verifier"]["name"], "oracle.pairwise_loss")
            csv_check = next(c for c in payload["checks"] if c["id"] == "csv_readable")
            self.assertEqual(csv_check["status"], "error")
            self.assertIsNone(payload["recomputed"])
            self.assertIn("Esito complessivo: ERROR",
                          summary_path.read_text(encoding="utf-8"))


class IsolationAndCli(unittest.TestCase):
    def test_source_does_not_call_models_or_eval_inputs(self):
        source = (ROOT / "src" / "oracle" / "pairwise_loss.py").read_text(
            encoding="utf-8")
        for banned in ("import orchestrator", "import vcc2026", "import requests",
                       "import urllib", "import openai", "import subprocess",
                       "eval(", "exec(", "import pickle", "field_size_limit"):
            self.assertNotIn(banned, source)

    def test_cli_writes_report_and_refuses_overwrite(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            report_path = tmp_path / "report.json"
            summary_path = tmp_path / "summary.txt"
            argv = [
                "--csv", str(FIXTURES / "example.csv"),
                "--candidate", str(FIXTURES / "correct_candidate.json"),
                "--config", str(FIXTURES / "config_default.json"),
                "--report", str(report_path),
                "--summary", str(summary_path),
            ]
            self.assertEqual(cli_main(argv), EXIT[PASS])
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["verdict"], "pass")
            self.assertIn("Esito complessivo: PASS",
                          summary_path.read_text(encoding="utf-8"))
            self.assertEqual(cli_main(argv), EXIT[ERROR])
            self.assertEqual(cli_main(argv + ["--force"]), EXIT[PASS])

    def test_cli_fail_exit_code(self):
        with tempfile.TemporaryDirectory() as tmp:
            argv = [
                "--csv", str(FIXTURES / "example.csv"),
                "--candidate", str(FIXTURES / "wrong_mean.json"),
                "--config", str(FIXTURES / "config_default.json"),
                "--report", str(Path(tmp) / "r.json"),
                "--summary", str(Path(tmp) / "s.txt"),
            ]
            self.assertEqual(cli_main(argv), EXIT[FAIL])

    def test_in_memory_empty_case_id_is_error(self):
        csv_bytes = b"case_id,loss_a,loss_b\n,0.20,0.30\n"
        candidate = (
            b'{"mean_loss_a": 0.20, "mean_loss_b": 0.30, '
            b'"mean_difference": -0.10, "conclusion": "A_lower"}'
        )
        report = verify_bytes(csv_bytes, candidate, None)
        self.assertEqual(report.verdict, ERROR)
        self.assertEqual(status(report, "identifiers"), ERROR)


if __name__ == "__main__":
    unittest.main()
