"""Six official members on HepG2 (development) for the C arms, with the effect -> export -> generation parity.

1. ``fitting_parity``: the C fits of HepG2 are recomputed with `fitting.py` (from the group means the run
   cached) and the effect-space indices of every HepG2 target are compared with the run's file.
2. ``export_parity``: each arm is written in the stage-100 format (targets, genes, ln lfc, observed);
   `vcc2026.bench.load_effects` must read back the same bits, and stage 45's own `read_effects` +
   `generate` must write the same cells as `vcc2026.inference.trial01_cells` for the same inputs and seed.
3. The six members: `vcc2026.bench.Bench` (truth = half A of each target's cells + all controls, replicate =
   half B, baseline = the scorer's generic profile), cells generated by trial-01 (t22/t25) from each arm.

Local scale, development line, not a VCC score.

    py.cmd six_member_hepg2.py --cube <cube_r1> --run <p3_c_r1> --protocol PROTOCOLLO.json --out <new folder>
"""
from __future__ import annotations

import argparse
import contextlib
import importlib.util
import io
import json
import sys
from pathlib import Path
from types import SimpleNamespace

import h5py
import numpy as np
import pandas as pd
import scipy.sparse as sp

from arms import Cube, gene_weight, table_means
from common import REPO, Timer, coords_path, data_root, git_state, h5_column, log, now_utc, sha256, write_json
from fitting import ReadOnlyGMCache, fit_c, predict_c
from metrics import blocks_of, score_table
from splits import Split, unit_hash

from vcc2026.bench import Bench, load_effects
from vcc2026.config import challenge
from vcc2026.inference import BasalProfile, trial01_cells

F32 = np.float32
ARMS = ['null', 'generic', 'transfer', 'tm0', 'm1', 'm1_swap', 'm2_0', 'm2', 'm2_swap']
GROUP, TABLE = 'HepG2', 'hepg2_nadig'


def load_stage45():
    spec = importlib.util.spec_from_file_location('stage45_for_parity', REPO / 'scripts' / '45_generate_prediction.py')
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def read_rows(path: Path, rows: np.ndarray, block: int = 2048) -> sp.csr_matrix:
    out = []
    with h5py.File(path, 'r') as f:
        x = f['X']
        for i in range(0, rows.size, block):
            out.append(sp.csr_matrix(np.asarray(x[rows[i:i + block]], dtype=F32)))
    return sp.vstack(out).tocsr()


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--cube', type=Path, required=True)
    p.add_argument('--run', type=Path, required=True, help='finished p3_run.py output (its gm_cache is read only)')
    p.add_argument('--protocol', type=Path, required=True)
    p.add_argument('--out', type=Path, required=True)
    p.add_argument('--targets', type=int, default=150)
    p.add_argument('--min-cells', type=int, default=50)
    p.add_argument('--cap-cells', type=int, default=64, help='cells read per target (stable draw)')
    p.add_argument('--max-controls', type=int, default=0,
                   help='controls read (stable draw; 0 = all): the scorer needs about 4 GB with all 4,976 here')
    p.add_argument('--seed', type=int, default=2026)
    p.add_argument('--gen-seed', type=int, default=20260912)
    a = p.parse_args()
    if a.out.exists():
        raise FileExistsError(a.out)
    timer = Timer()
    proto = json.loads(a.protocol.read_text(encoding='utf-8'))
    P = proto['parameters']
    cube = Cube(a.cube, min_cells=P['min_cells'])
    coords = pd.read_csv(coords_path(P['gene_coordinates']), sep='\t')
    ens_to_sym = {str(gid).split('.')[0]: s for s, gid in zip(coords['symbol'], coords['gene_id']) if isinstance(gid, str)}
    a.out.mkdir(parents=True)
    commons, raw_means = table_means(cube, Split('C', '__none__', None, P['n_folds']))
    fitted = fit_c(cube, GROUP, P, commons, raw_means, ReadOnlyGMCache(cube, commons, a.run / 'gm_cache'))
    fits_run = json.loads((a.run / 'fits.json').read_text(encoding='utf-8'))[GROUP]
    swap_group = fits_run['swap_group']
    log(f'HepG2 refit: m2 k={fitted["k"]} d={fitted["d"]} ridge={fitted["ridge"]} (run: {fits_run["m2_choice"]})')

    # 1. fitting parity on the effect-space indices
    run_rows = pd.read_csv(a.run / f'per_target_C_{GROUP}.csv.gz', keep_default_na=False, na_values=['', 'nan', 'NaN'])
    keys = cube.keys_of(TABLE)
    diffs = {}
    for blk in blocks_of(keys, P['pds_block']):
        bkeys = [keys[i] for i in blk]
        res = predict_c(cube, fitted, TABLE, bkeys, commons, swap_group)
        if res is None:
            continue
        truth, _ = cube.get(TABLE, 'raw', res['keys'], purpose='truth')
        se, _ = cube.get(TABLE, 'se', res['keys'], purpose='truth')
        w = gene_weight(cube.basal[TABLE])
        tpos = cube.target_gene_positions(res['keys'], ens_to_sym)
        for name, pred in res['arms'].items():
            sc = score_table(pred, truth, se, w, res['keys'], tpos, block_size=len(res['keys']))
            ref = run_rows[run_rows.arm == name].set_index('target_key').reindex(res['keys'])
            for m, v in sc.items():
                d = np.abs(np.nan_to_num(v, nan=-9) - np.nan_to_num(ref[m].to_numpy(float), nan=-9))
                diffs[(name, m)] = max(diffs.get((name, m), 0.0), float(d.max()))
    worst = max(diffs.values())
    write_json(a.out / 'fitting_parity.json', dict(
        what='HepG2 effect-space indices recomputed through fitting.py against the run file',
        run=str(a.run), max_abs_difference=worst, by_arm_metric={f'{k[0]}:{k[1]}': v for k, v in diffs.items()},
        passed=bool(worst <= 1e-6)))
    log(f'fitting parity: max abs difference {worst:.3g}')
    if worst > 1e-6:
        raise AssertionError('fitting.py does not reproduce the run; six members not computed')

    # 2. targets and cells
    rows = cube.rows[TABLE]
    usable = rows[rows.usable & (rows.n_cells >= a.min_cells)]
    chosen = sorted(usable.target_key, key=lambda k: unit_hash(k, 'six-member'))
    res = predict_c(cube, fitted, TABLE, chosen, commons, swap_group)
    chosen = res['keys'][:a.targets]
    sym = dict(zip(rows.target_key, rows.target))
    labels = [sym[k] for k in chosen]
    final = predict_c(cube, fitted, TABLE, chosen, commons, swap_group)
    if final['keys'] != chosen:
        raise AssertionError('the chosen targets lost transfer support')
    preds, s_finite = final['arms'], final['s_finite']
    hepg2 = Path(json.loads((Path(str(a.cube)).parent / 'hepg2_r2' / 'manifest.json').read_text(encoding='utf-8'))['input']['path'])
    with h5py.File(hepg2, 'r') as f:
        cell_gene = h5_column(f['obs/gene'])
        native = h5_column(f['var/gene_name'])
    rng = np.random.default_rng(a.seed)
    target_rows = {}
    for lab in labels:
        r = np.flatnonzero(cell_gene == lab)
        if r.size > a.cap_cells:
            r = np.sort(rng.choice(r, a.cap_cells, replace=False))
        target_rows[lab] = r
    ctrl = np.flatnonzero(cell_gene == 'non-targeting')
    if a.max_controls and ctrl.size > a.max_controls:
        ctrl = np.sort(np.random.default_rng(a.seed + 1).choice(ctrl, a.max_controls, replace=False))
    all_rows = np.sort(np.concatenate(list(target_rows.values()) + [ctrl]))
    log(f'reading {all_rows.size} HepG2 cells ({len(labels)} targets, {ctrl.size} controls)')
    x = read_rows(hepg2, all_rows)
    remap = {r: i for i, r in enumerate(all_rows)}
    target_rows = {t: np.array([remap[r] for r in v]) for t, v in target_rows.items()}
    ctrl_rows = np.array([remap[r] for r in ctrl])

    # 3. export in the stage-100 format and parity of the export and of the generator
    cube_pos = pd.Index(cube.genes).get_indexer(native)
    have = cube_pos >= 0
    effects_dir = a.out / 'effects'
    effects_dir.mkdir()
    exported = {}
    for arm in ARMS:
        pred = preds[arm]
        lfc = np.zeros((len(chosen), native.size), F32)
        obs = np.zeros((len(chosen), native.size), bool)
        lfc[:, have] = np.nan_to_num(pred[:, cube_pos[have]], nan=0.0)
        if arm == 'transfer':
            obs[:, have] = s_finite[:, cube_pos[have]]
        elif arm != 'null':
            obs[:, have] = np.isfinite(pred[:, cube_pos[have]])
        lfc[~obs] = 0.0
        path = effects_dir / f'effects_{arm}.npz'
        np.savez_compressed(path, targets=np.array(labels), genes=np.array(native), lfc=lfc, observed=obs)
        back = load_effects([f'x={path}'], native, with_observed=True)['x']
        same = all(np.array_equal(back[t][0].astype(F32), lfc[i]) and np.array_equal(back[t][1], obs[i])
                   for i, t in enumerate(labels))
        exported[arm] = dict(file=path.name, sha256=sha256(path), roundtrip_identical=bool(same),
                             observed_share=float(obs.mean()))
        if not same:
            raise AssertionError(f'{arm}: load_effects does not read back the exported effects')
    ctrl_x = x[ctrl_rows]
    basal = BasalProfile(context='HepG2', profile=np.asarray(ctrl_x.sum(0), dtype=np.float64).ravel(),
                         library_sizes=np.asarray(ctrl_x.sum(1)).ravel().astype(np.int64), n_cells=int(ctrl_rows.size),
                         nnz_per_cell=np.diff(ctrl_x.indptr).astype(np.int32))
    ch = challenge()
    stage = load_stage45()

    class Axis:
        def __init__(self, symbols):
            self.symbols = list(symbols)

        def __len__(self):
            return len(self.symbols)

    probe = labels[:3]
    n_probe = 20
    with contextlib.redirect_stdout(io.StringIO()):
        preds45 = stage.read_effects({'HepG2': effects_dir / 'effects_m1.npz'}, probe, Axis(native), 1.0)
        stage.generate(a.out / 'parity_stage45.h5ad', Axis(native),
                       SimpleNamespace(pert_col='target_gene', context_col='context',
                                       max_stored_per_cell=ch.max_stored_per_cell,
                                       max_counts_per_cell=ch.max_counts_per_cell),
                       ('HepG2',), probe, {'HepG2': basal}, preds45, {}, None, n_probe, np.random.default_rng(a.gen_seed))
    with h5py.File(a.out / 'parity_stage45.h5ad', 'r') as f:
        whole = sp.csr_matrix((f['X/data'][:], f['X/indices'][:], f['X/indptr'][:]),
                              shape=(len(probe) * n_probe, native.size))
    eff = load_effects([f'x={effects_dir / "effects_m1.npz"}'], native, with_observed=True)['x']
    stream = np.random.default_rng(a.gen_seed)
    identical = True
    for i, t in enumerate(probe):
        mine, _ = trial01_cells(basal.profile, *eff[t], basal.library_sizes, n_probe, stream,
                                max_stored_per_cell=ch.max_stored_per_cell, max_counts_per_cell=ch.max_counts_per_cell)
        mine = mine.tocsr()
        mine.eliminate_zeros()
        mine.sort_indices()
        w = whole[i * n_probe:(i + 1) * n_probe]
        identical &= bool(np.array_equal(w.indptr, mine.indptr) and np.array_equal(w.indices, mine.indices)
                          and np.array_equal(w.data, mine.data.astype(F32)))
    (a.out / 'parity_stage45.h5ad').unlink()
    write_json(a.out / 'export_parity.json', dict(
        written_utc=now_utc(), exported=exported,
        generator_parity=dict(arm='m1', targets=probe, cells_per_target=n_probe, seed=a.gen_seed,
                              stage45_vs_trial01_bit_identical=identical,
                              checks='gene order (native HepG2 axis), ln -> log2 in stage 45, observed mask, '
                                     'compositional shift, log2 clip 6, Poisson, storage and count caps'),
        tolerance='exact equality required (bits)', passed=bool(identical and all(v['roundtrip_identical']
                                                                                for v in exported.values()))))
    log(f'export parity: generator identical={identical}')
    if not identical:
        raise AssertionError('stage 45 and trial01_cells disagree on the exported effects')

    # 4. the six members
    bench = Bench(x, target_rows, ctrl_rows, native, a.out / 'bench', seed=a.seed)
    bench.anchors()
    effects = {arm: load_effects([f'x={effects_dir / f"effects_{arm}.npz"}'], native, with_observed=True)['x']
               for arm in ARMS}
    for arm in ARMS:
        stream = np.random.default_rng(a.gen_seed)
        blocks, labs = [], []
        for t in bench.targets:
            n = bench.n_pred(t)
            cells, _ = trial01_cells(basal.profile, *effects[arm][t], basal.library_sizes, n, stream,
                                     max_stored_per_cell=ch.max_stored_per_cell,
                                     max_counts_per_cell=ch.max_counts_per_cell)
            blocks.append(cells)
            labs.append(np.full(n, t))
        bench.score(arm, sp.vstack(blocks).tocsr(), np.concatenate(labs))
        log(f'{arm} scored ({timer()} s)')
    table = bench.finish(dict(stage='risposta_contesto six_member_hepg2', targets=labels, target_keys=chosen,
                              cap_cells=a.cap_cells, min_cells=a.min_cells, seed=a.seed, gen_seed=a.gen_seed,
                              max_controls=a.max_controls,
                              generator='trial-01 (vcc2026.inference.trial01_cells, Poisson)',
                              protocol_sha256=sha256(a.protocol), run=str(a.run)))
    write_json(a.out / 'run.json', dict(written_utc=now_utc(), git=git_state(), seconds=timer(),
                                        arguments={k: str(v) for k, v in vars(a).items()}))
    log('done')


if __name__ == '__main__':
    main()
